### ISSUE TITLE
Whether the camera intrinsic parameters can be provided？

### ISSUE THREAD

**Issue by Lsen991031** [zhenzhiwang/HumanVid#11]

**Comment by zhenzhiwang** [comment]
They are locations and quaternions for extrinsics.

**Comment by Lsen991031** [comment]
Alright, I asked the wrong question. What I actually wanted to ask is whether the camera intrinsic parameters can be provided, or did you discard the intrinsic parameters when you were tracking?

**Comment by zhenzhiwang** [comment]
Please refer to this issue https://github.com/zhenzhiwang/HumanVid/issues/10#issuecomment-2336564593. The intrinsic of internet videos are unknown, therefore we can only set heurisitic values. For synthetic data, we will provide both intrinsic and extrinsic parameters.
