### ISSUE TITLE
The camera intrinsics for the videos in pixels

### ISSUE THREAD

**Issue by liuxiaoyu1104** [zhenzhiwang/HumanVid#12]
In cameractrl，the camera intrinsics are used for ray_condition and expressed in resolution-independent normalized coordinates（such as 0.474812461 0.844111024 0.500000000 0.500000000）.

As mentioned by the author in issue 10，the camera is a standard 36mm CMOS full-frame camera, we use 50mm focal length for horizontal videos.
the camera intrinsics for horizontal videos should be as follows:
fx =  focal length in mm / sensor width in mm  = 50/36 = 1.388889
fy =  focal length in mm / sensor width in mm  =  50/24 = 2.083333
cx =0.5
cy =0.5

And the intrinsics matrix of the videos in pixels is[width · fx，height · focal_length_y，width · principal_point_x，height · principal_point_y ]

The way to obtained the camera intrinsics for the videos in pixels, as mentioned above, is correct？

**Comment by zhenzhiwang** [comment]
Yes, you are correct.
