### ISSUE TITLE
How did you train animate anyone on your dataset? Did you only use the static camera video or use all the video?

### ISSUE THREAD

**Issue by River-Zhang** [zhenzhiwang/HumanVid#16]
I find that some part of the videos in your dataset has dynamic camera motions. Did you also use these to train animate anyone and do I need to consider the camera pose if I want to retrain Animate Anyone?

Thanks for your fantastic work!

**Comment by River-Zhang** [comment]
Could you please provide some detail about how you combine camera pose while training animate anyone?

**Comment by zhenzhiwang** [comment]
By adding a camera pose encoder in CameraCtrl and add the camera embedding to the human pose embedding in Animate Anyone for injecting control signals. The camera pose encoder is pretrained by CameraCtrl on RealEstate10K.
