### ISSUE TITLE
Architecture of the model

### ISSUE THREAD

**Issue by Yuancheng-Xu** [zhenzhiwang/HumanVid#18]
Congratulations on the cool work! I have a few questions about the architecture in terms of the camera conditions. 

In Figure 4,
1. Why is the Plucker Embedding size = 6 * H * W? Should it be f * 6 * H * W, where f is the number of frames so that it represents the camera trajectory? 
2. It seems that the camera encoding is directly concatenated with the noise. This is very different from CameraCtrl, where the camera encoding is injected into each layer of the temporal embedding. Is my understanding correct and if it is, I wonder why you chose this design.

Thank you in advance!

**Comment by zhenzhiwang** [comment]
Hi Yuancheng,
Thanks for your interest of our work.
(1) Yes, 6 * H * W is for single frame, f * 6 * H * W is for video.
(2) The injection of camera encoding is very similar to the injection of pose condition in Moore-AnimateAnyone. Actually it is different from CameraCtrl, as CameraCtrl is purely controlnet style (i.e., freezing the Unet) and our model is not (i.e., finetuning the Unet).
Please feel free to comment if you have further questions.

**Comment by Yuancheng-Xu** [comment]
Thanks for the clarification! I am wondering if the model will be released?

**Comment by zhenzhiwang** [comment]
Yeah. We have the plan to release code and ckpt. But recently the 1-st author is working on another project. Hopefully the code release will be done in Jan or Feb 2025.
