### ISSUE TITLE
Retargeting motions to Openpose keypoint format

### ISSUE THREAD

**Issue by julkaztwittera** [zhenzhiwang/HumanVid#3]
Hi,
fantastic work!
I wonder how did you retarget standard motions from Blender/Rokoko to Openpose keypoint format? Haven't found any good solution for this problem.

**Comment by zhenzhiwang** [comment]
Hi,
Currently we have implemented the convertion from SMPL-X 3D skeleton to openpose keypoints, by first projecting the 3D skeleton to 2D skeleton in the camera space and then reorder the keypoints to fit the openpose format. For motion with other format, I think it is standard to convert other motions to SMPL-X format. We will also open-source such code later. Stay tuned!

**Comment by zhenzhiwang** [comment]
Hi [julkaztwittera](https://github.com/julkaztwittera),

We have released the script to convert 3D SMPL-X keypoints to 2D SMPL-X keypoints in the camera space (from Bedlam repo), and the script to re-organize keypoints to fit the commonly used COCO keypoints for skeleton visualization similar to DWPose's results. Please check the python scripts in this repo.
