### ISSUE TITLE
合成数据对效果的提升是多少？

### ISSUE THREAD

**Issue by YSShannon** [zhenzhiwang/HumanVid#4]
![image](https://github.com/user-attachments/assets/3a5f40e9-ef51-4162-b302-120dcf1de8b4)
你好，目前看到论文中demo效果比较好，但是论文中有三个不同数据源，不知道这三个数据单独的效果有没做消融实验，特别是3D的合成数据的效果有对整体效果多大提升，主要体现在哪方面的提升

**Comment by zhenzhiwang** [comment]
Hi,
Thanks for your interest. The synthetic data mainly improve the camera encoder's accuracy, e.g., the generated videos follow the camera parameters more precisely.

Besides, please use English to raise an issue.  Thanks.
