### ISSUE TITLE
Model weights release

### ISSUE THREAD

**Issue by moteloumka** [zhenzhiwang/HumanVid#5]
Thank you for releasing such an interesting paper! You're saying that you're planning to release the training code and the data from your research, but will the model weights be released?

**Comment by zhenzhiwang** [comment]
Yes, we plan to release ckpt in the future.

**Comment by moteloumka** [comment]
Super, thank you for your quick response! Any idea when you plan on doing it? Wouldn't like to miss the occasion.

**Comment by zhenzhiwang** [comment]
Thank you for your interest in our paper. The specific date of ckpt release will depends on the paper submission results. But the data will be definitely  released earlier than the ckpt.
