### ISSUE TITLE
dataset url seems to be broken

### ISSUE THREAD

**Issue by ArtemisZGL** [zhenzhiwang/HumanVid#9]
I downloaded the url file and try to download the video, but all of them became "Oops, we couldn't find this page."

**Comment by ArtemisZGL** [comment]
I tried to remove the "download" and found the video can be reached.

**Comment by zhenzhiwang** [comment]
I use `r = requests.get(url)` to download video and save them by open a mp4 file `outfile` and use `outfile.write(r.content)`. The urls in the txt files work well. Maybe your download script has a little difference with mine.
